name: Terminal CV Formatter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Downlod dependencies
        run: |
          export SIMPLE_MD_CV="./cv/2025/NicolasCouture-short.md"
          [[ -f "${SIMPLE_MD_CV}" ]] || {
            echo "error: file not found: ${SIMPLE_MD_CV}"
            exit 1
          }
          DEBIAN_FRONTEND=non-interactive sudo apt-get install -qqy md2term

      - name: Nicolas Couture - Simple Markdown CV
        run: |
          exec /bin/bash -c 'export SIMPLE_MD_CV="./NicolasCouture-simple.md";
          echo "―――――――――――― Nicolas Couture Simple Markdown CV ――――――――――――";
          md2term -c -k1 -f "${SIMPLE_MD_CV}";
          echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――";'
