name: Terminal CV Formatter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display my Simple CV in Markdown format using colored terminal formatting tool in GitHub Action logs.
        run: |
          export SIMPLE_MD_CV="./NicolasCouture-simple.md"
          [[ -f "${SIMPLE_MD_CV}" ]] || {
            echo "error: file not found: ${SIMPLE_MD_CV}"
            exit 1
          }
          DEBIAN_FRONTEND=non-interactive sudo apt-get install -qqy md2term
          echo "―――――――――――― Nicolas Couture Simple Markdown CV ――――――――――――"
          md2term -c -k1 -f "${SIMPLE_MD_CV}"
          echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
